#!/bin/bash

# Script to ensure required libraries and external commands for the WeatherHills.

function die
{
    # Echo message and exit script.
    # Arguments: optional message, optional exit code
    echo "${1:-"Unknown Error"}" 1>&2
    exit ${2:-1}
}


# Test that external executables are present
conda -V || die "Please install Anaconda or Miniconda from http://continuum.io/downloads into your PATH"

if [ `conda info --envs | grep -c '^weather_hills '` == 0 ]
then
  conda create -n weather_hills --yes python=2.7 pip
fi

conda install -n weather_hills --yes \
  numpy=1.8.0 \
  netcdf4=1.0.7 \
  matplotlib=1.3.1 \
  sqlalchemy=0.9.2 \
  psycopg2=2.4 \
  mock=1 \
  nose=1.3 \
  pyyaml=3.10 \
  dateutil=2.1 \
  requests=2.2.1\
  flask=0.10.1 || die "Conda command failed"

. activate weather_hills || die
pip install \
  gunicorn==18 \
  blinker==1.3 \
  rednose==0.4.1 \
  alembic==0.6.3 || die "pip install failed"
. deactivate

echo "Requirements Installed"
